SELECT CONVERT(VARCHAR, OrderID) AS OrderID FROM OrderDetails
UNION ALL
SELECT CONVERT(VARCHAR, OrderID) AS ORDERID FROM Orders			
ORDER BY OrderID

SELECT CONVERT(VARCHAR, ContactName) AS ContactName FROM Customers
UNION ALL
SELECT CONVERT(VARCHAR, ContactName) AS ContactName FROM Suppliers		
ORDER BY ContactName